# run: conda env create --file environment.yml
name: homework-1-behavioral-data-science
dependencies:
  - python == 3.12
  - pip
  - pip:
    - matplotlib >= 3.10.0
    - numpy ~= 1.26.3
    - seaborn >= 0.13.2
    - scipy >= 1.15.1
    - pandas >= 2.2.3
    - scikit-learn >= 1.6.1
    - ipython >= 8.26.0
    - ipywidgets >= 8.1.5
    - notebook >= 7.3.2
    - tensorflow >= 2.17.0
